### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by IamMegatron2025** [sorelyss/image2text#1]
hello, how to use your code? can you provide some introduction?
thank you very much!

**Comment by sorelyss** [comment]
Hi, I'm sorry for the delay. I left a readme file of the repository. I just changed few things from the original google's repository.  I also used this code in the [PDI repository](https://github.com/sorelyss/PDI/tree/master/Final_Project).

**Comment by IamMegatron2025** [comment]
@sorelyss thank for your reply.
